<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apache.seatunnel</groupId>
        <artifactId>seatunnel</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>seatunnel-dist</artifactId>
    <name>SeaTunnel : Dist</name>

    <properties>
        <!-- disable mvn deploy to central maven repo by default -->
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <build>
        <finalName>apache-seatunnel-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>bin</id>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assembly/assembly-bin-ci.xml</descriptor>
                            </descriptors>
                            <appendAssemblyId>true</appendAssemblyId>
                            <attach>false</attach>
                        </configuration>
                    </execution>
                    <execution>
                        <id>src</id>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assembly/assembly-src.xml</descriptor>
                            </descriptors>
                            <appendAssemblyId>true</appendAssemblyId>
                            <attach>false</attach>
                        </configuration>
                    </execution>

                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>seatunnel-business</id>
            <activation>
                <activeByDefault>true</activeByDefault>
                <property>
                    <name>release</name>
                    <value>false</value>
                </property>
            </activation>
            <properties>
                <mysql.version>8.0.27</mysql.version>
                <postgresql.version>42.6.2</postgresql.version>
                <postgis.jdbc.version>2.5.1</postgis.jdbc.version>
                <dm-jdbc.version>8.1.2.141</dm-jdbc.version>
                <sqlserver.version>9.2.1.jre8</sqlserver.version>
                <oracle.version>12.2.0.1</oracle.version>
                <sqlite.version>3.39.3.0</sqlite.version>
                <db2.version>db2jcc4</db2.version>
                <sqlite.version>3.42.0.0</sqlite.version>
                <tablestore.version>5.13.9</tablestore.version>
                <saphana.version>2.23.10</saphana.version>
                <teradata.version>17.20.00.12</teradata.version>
                <redshift.version>2.1.0.9</redshift.version>
                <informix-client.version>1.1.3</informix-client.version>
                <snowflake.version>3.13.29</snowflake.version>
                <dws-gaussdb.version>8.2.1.300-200</dws-gaussdb.version>
                <iceberg-aws.version>1.4.2</iceberg-aws.version>
                <software.amazon.version>2.27.12</software.amazon.version>
                <oceanbase.version>2.4.3</oceanbase.version>
                <snowflake.version>3.13.29</snowflake.version>

                <!-- Imap storage dependency package  -->
                <hadoop-aliyun.version>3.3.6</hadoop-aliyun.version>
                <json-smart.version>2.4.7</json-smart.version>
                <hadoop-aws.version>3.3.6</hadoop-aws.version>
                <aws-java-sdk.version>1.12.692</aws-java-sdk.version>
                <netty-buffer.version>4.1.89.Final</netty-buffer.version>
                <hive.exec.version>3.1.3</hive.exec.version>
                <hive2.exec.version>2.1.1</hive2.exec.version>
                <hive.jdbc.version>3.1.3</hive.jdbc.version>
                <aliyun.sdk.oss.version>3.13.2</aliyun.sdk.oss.version>
                <jdom.version>2.0.6</jdom.version>

                <dolphindb-javaapi.version>3.00.2.6</dolphindb-javaapi.version>
                <dolphindb-jdbc.version>3.00.2.1</dolphindb-jdbc.version>
                <tidb.version>3.3.5</tidb.version>
                <gbase8s.version>3.6.3.2</gbase8s.version>
            </properties>
            <dependencies>
                <!-- starters -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-starter</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>checkpoint-storage-hdfs</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>imap-storage-file</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <!-- transforms -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-transforms-v2</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <!-- connectors -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-mongodb</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-iceberg</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-fake</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-selectdb-cloud</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-console</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-http-base</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-file-oss</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-hive1</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-hive2</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-hive3</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-hw-mrs-hive3</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-file-hadoop</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-file-s3</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-file-local</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-file-ftp</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-file-sftp</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-assert</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-kafka-wt</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-jdbc</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-sapbw</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-jdbc-hive3</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-jdbc-hive1</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-jdbc-hive2</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-jdbc-inceptor</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-jdbc-phoenix</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-jdbc-starrocks</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-jdbc-cdh-hive2</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-elasticsearch</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-starrocks</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-clickhouse</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-tablestore</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-doris</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-mysql</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-informix-wt</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-s3-redshift-wt</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-mongodb</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-postgres</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-opengauss-wt</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-highgo-wt</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-oracle-wt</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-agent-oracle-wt</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-dameng-wt</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-maxcompute</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-emqx</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-dws-gaussdb-wt</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-sqlserver</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-tidb</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-pi</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-dolphindb-wt</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-paimon</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-amazonsqs</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-redis</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-argodb</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-pi</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-pi-metadata</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <!-- jdbc driver -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-phoenix-5.1.3-hadoop3.3.6-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>mysql</groupId>
                    <artifactId>mysql-connector-java</artifactId>
                    <version>${mysql.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.postgresql</groupId>
                    <artifactId>postgresql</artifactId>
                    <version>${postgresql.version}</version>
                    <scope>provided</scope>
                </dependency>
                <!-- postgis and huaweicloud-dws-jdbc can not use together -->
                <!--                <dependency>-->
                <!--                    <groupId>net.postgis</groupId>-->
                <!--                    <artifactId>postgis-jdbc</artifactId>-->
                <!--                    <version>${postgis.jdbc.version}</version>-->
                <!--                    <scope>provided</scope>-->
                <!--                </dependency>-->
                <dependency>
                    <groupId>com.dameng</groupId>
                    <artifactId>DmJdbcDriver18</artifactId>
                    <version>${dm-jdbc.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.sap.cloud.db.jdbc</groupId>
                    <artifactId>ngdbc</artifactId>
                    <version>${saphana.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.microsoft.sqlserver</groupId>
                    <artifactId>mssql-jdbc</artifactId>
                    <version>${sqlserver.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.oracle.database.jdbc</groupId>
                    <artifactId>ojdbc8</artifactId>
                    <version>${oracle.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.oracle.database.xml</groupId>
                    <artifactId>xdb6</artifactId>
                    <version>${oracle.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.oracle.database.xml</groupId>
                    <artifactId>xmlparserv2</artifactId>
                    <version>${oracle.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.oracle.database.nls</groupId>
                    <artifactId>orai18n</artifactId>
                    <version>${oracle.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.xerial</groupId>
                    <artifactId>sqlite-jdbc</artifactId>
                    <version>${sqlite.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.ibm.db2.jcc</groupId>
                    <artifactId>db2jcc</artifactId>
                    <version>${db2.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.aliyun.openservices</groupId>
                    <artifactId>tablestore-jdbc</artifactId>
                    <version>${tablestore.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>com.teradata.jdbc</groupId>
                    <artifactId>terajdbc4</artifactId>
                    <version>${teradata.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.iceberg</groupId>
                    <artifactId>iceberg-aws</artifactId>
                    <version>${iceberg-aws.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>com.amazon.redshift</groupId>
                    <artifactId>redshift-jdbc42</artifactId>
                    <version>${redshift.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>net.snowflake</groupId>
                    <artifactId>snowflake-jdbc</artifactId>
                    <version>${snowflake.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.tikv</groupId>
                    <artifactId>tikv-client-java</artifactId>
                    <version>${tidb.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>com.ibm.informix</groupId>
                    <artifactId>ifx-changestream-client</artifactId>
                    <version>${informix-client.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.kingbase8</groupId>
                    <artifactId>kingbase8</artifactId>
                    <version>8.2.0</version>
                    <scope>system</scope>
                    <systemPath>${basedir}/src/main/kingbase/kingbase8-8.2.0.jar</systemPath>
                </dependency>

                <dependency>
                    <groupId>org.opengauss</groupId>
                    <artifactId>opengauss-jdbc</artifactId>
                    <version>5.0.1</version>
                    <scope>system</scope>
                    <systemPath>${basedir}/src/main/opengauss/opengauss-jdbc-5.0.1.jar</systemPath>
                </dependency>

                <dependency>
                    <groupId>com.highgo</groupId>
                    <artifactId>highgo-jdbc</artifactId>
                    <version>6.2.0</version>
                    <scope>system</scope>
                    <systemPath>${basedir}/src/main/highgo/hgjdbc-6.2.0.jar</systemPath>
                </dependency>

                <dependency>
                    <groupId>io.transwarp.inceptor</groupId>
                    <artifactId>inceptor-jdbc-relocation</artifactId>
                    <version>8.31.1</version>
                    <scope>system</scope>
                    <systemPath>${basedir}/src/main/inceptor/inceptor-jdbc-relocation-8.31.1.jar</systemPath>
                </dependency>

                <dependency>
                    <groupId>com.huaweicloud.dws</groupId>
                    <artifactId>huaweicloud-dws-jdbc</artifactId>
                    <version>${dws-gaussdb.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.oceanbase</groupId>
                    <artifactId>oceanbase-client</artifactId>
                    <version>${oceanbase.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.gbasedbt</groupId>
                    <artifactId>jdbc</artifactId>
                    <version>${gbase8s.version}</version>
                    <scope>provided</scope>
                </dependency>
                <!-- jdbc driver end -->

                <dependency>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-buffer</artifactId>
                    <version>${netty-buffer.version}</version>
                    <scope>provided</scope>
                </dependency>

                <!-- hadoop jar -->
                <dependency>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-aws</artifactId>
                    <version>${hadoop-aws.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-java-sdk-bundle</artifactId>
                    <version>${aws-java-sdk.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>software.amazon.awssdk</groupId>
                    <artifactId>bundle</artifactId>
                    <version>${software.amazon.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-aliyun</artifactId>
                    <version>${hadoop-aliyun.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-client</artifactId>
                    <version>${hadoop2.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.aliyun.oss</groupId>
                    <artifactId>aliyun-sdk-oss</artifactId>
                    <version>${aliyun.sdk.oss.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.jdom</groupId>
                    <artifactId>jdom2</artifactId>
                    <version>${jdom.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hadoop2-2.6.5-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hadoop3-3.0.0-cdh6.3.2-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hadoop3-3.1.4-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hadoop3-3.3.6-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <!-- hadoop jar end -->
                <!-- hive jar start -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-exec-1.2.1-hadoop2.6.5-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-exec-2.1.1-cdh6.3.2-hadoop3.0.0-cdh6.3.2-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-exec-2.1.1-hadoop2.6.5-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-exec-2.3.9-hadoop3.1.4-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-exec-3.1.3-hadoop3.3.6-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-exec-mrs-3.1.0-h0.cbu.mrs.320.r33-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>org.slf4j</groupId>
                            <artifactId>slf4j-reload4j</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <!-- hive jdbc jar -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-jdbc-1.2.1-hadoop2.6.5-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-mrs-3.1.1-hw-ei-315008-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-jdbc-2.1.1-cdh6.3.2-hadoop3.0.0-cdh6.3.2-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-jdbc-2.1.1-hadoop2.6.5-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-jdbc-2.3.9-hadoop3.1.4-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hive-jdbc-3.1.3-hadoop3.3.6-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <!-- hive jar end -->

                <dependency>
                    <groupId>com.dolphindb</groupId>
                    <artifactId>dolphindb-javaapi</artifactId>
                    <version>${dolphindb-javaapi.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>com.dolphindb</groupId>
                    <artifactId>jdbc</artifactId>
                    <version>${dolphindb-jdbc.version}</version>
                    <scope>provided</scope>
                </dependency>

                <!-- argodb jar -->
                <dependency>
                    <groupId>io.transwarp.inceptor</groupId>
                    <artifactId>argodb-sink-client</artifactId>
                    <version>8.37.3</version>
                </dependency>
                <dependency>
                    <groupId>io.transwarp.inceptor</groupId>
                    <artifactId>inceptor-jdbc-shaded-with-relocation</artifactId>
                    <version>8.37.3</version>
                    <scope>system</scope>
                    <systemPath>${basedir}/src/main/argodb/inceptor-jdbc-shaded-with-relocation-8.37.3.jar</systemPath>
                </dependency>
                <dependency>
                    <groupId>com.sap</groupId>
                    <artifactId>sapjco3</artifactId>
                    <version>3.0.10</version>
                    <scope>system</scope>
                    <systemPath>${basedir}/src/main/sapbw/sapjco3.jar</systemPath>
                </dependency>
            </dependencies>
            <repositories>
                <repository>
                    <id>cloudera</id>
                    <url>https://repository.cloudera.com/artifactory/cloudera-repos/</url>
                </repository>
            </repositories>
        </profile>
    </profiles>
</project>
